USE [master]
GO

/****** Object:  Database [AGENDA]    Script Date: 24/04/2020 16:15:59 ******/
CREATE DATABASE [AGENDA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AGENDA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AGENDA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AGENDA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\AGENDA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AGENDA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AGENDA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AGENDA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AGENDA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AGENDA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AGENDA] SET ARITHABORT OFF 
GO

ALTER DATABASE [AGENDA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AGENDA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AGENDA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AGENDA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AGENDA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AGENDA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AGENDA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AGENDA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AGENDA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AGENDA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AGENDA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AGENDA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AGENDA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AGENDA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AGENDA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AGENDA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AGENDA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AGENDA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AGENDA] SET  MULTI_USER 
GO

ALTER DATABASE [AGENDA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AGENDA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AGENDA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AGENDA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AGENDA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AGENDA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AGENDA] SET  READ_WRITE 
GO

